name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: ${{ matrix.os }} jdk-${{ matrix.java }} unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [8, 11]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - run: sbt coverage test coverageReport
        shell: bash
      - run: pip install --user coverage
        shell: bash
      - run: codecov
        shell: bash
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
